## 1 - Import NumPy as np

In [6]:
import numpy as np

## 2 - Create an array of 10 zeros

In [19]:
a=np.zeros((10),dtype=np.int64)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 3 - Create an array of 10 ones

In [18]:
b=np.ones((10),dtype=np.int64)
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 4 - Create an array of 10 fives

In [17]:
c=np.linspace(5,5,num=10,dtype=np.int64)
c

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5 - Create an array of the integers from 10 to 50

In [4]:
d=np.linspace(10,50,num=40,dtype=np.int64)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 50])

## 6 - Create an array of all the even integers from 10 to 50

In [25]:
e=np.arange(10,50,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

## 7 - Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
f=np.arange(0,8+1).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 8 - Create a 3x3 identity matrix

In [31]:
g=np.identity(3,dtype=np.int64)
g

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 9 - Use NumPy to generate a random number between 0 and 1

In [67]:
h=np.random.random()
h

0.06918087402544437

## 10 - Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [68]:
i = np.random.standard_normal(25)
i

array([-0.30480593, -0.04274136,  0.980998  ,  1.17871586,  0.32664908,
       -0.38788413, -2.3682601 ,  1.37229738, -1.39920998,  0.30474947,
        1.6035618 ,  1.20170804, -0.26211279,  0.45954748,  0.30300606,
       -2.68602184, -1.28153052, -0.05020241,  0.16333024,  0.79144963,
       -0.06880435, -1.83726288, -0.29636401,  0.11116625,  1.24375383])

## 11 - Create the following matrix:
### Create an array of 20 linearly spaced points between 0 and 1

In [72]:
j=np.linspace(0,1,num=20)
j

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## 12 - Numpy Indexing and Selection
### Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
### mat = np.arange(1,26).reshape(5,5)

In [7]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following
### 12.1 - Get the sum of all the values in mat

In [8]:
k=np.sum(mat,axis=None)
k

325

### 12.2 - Get the standard deviation of the values in mat

In [99]:
l=np.std(mat, axis=None)
l

7.211102550927978

### 12.3 - Get the sum of all the columns in mat

In [101]:
m=np.sum(mat,axis=0)
m

array([55, 60, 65, 70, 75])